FROM ubuntu:16.04

# Install.

RUN \
  apt-get update && \
  apt-get -y upgrade && \
  DEBIAN_FRONTEND=noninteractive apt-get install -q -y postfix && \
  apt-get install -y nginx php php-pgsql  php-gd php-curl php-fpm php-cgi php-cli php-zip apache2-utils  && \
  apt-get install -y supervisor  postgresql-client postgresql-client-common postgresql-contrib && \
  apt-get install -y php-memcached php-soap php-ctype  php-zip php-simplexml  php-dom php-xml php-json php-intl php-fpm php-common php-mbstring php-xmlrpc php-soap php-gd php-xml php-intl php-mysql php-cli php-mcrypt php-ldap php-zip php-curl libpq-dev  rsyslog  && \
  apt-get install -y curl git htop man unzip vim wget



RUN useradd -ms /bin/bash elearning
RUN mkdir /home/elearning/moodle
RUN chown -R elearning:elearning /home/elearning/moodle

COPY --chown=www-data:www-data . /var/www/html/
RUN chown www-data:www-data /var/www
RUN chown -R www-data:www-data /var/www/*
RUN mkdir /var/www/html/localcache
RUN chown www-data:www-data /var/www/html/localcache
CMD ["postconf","compatibility_level=2"]
CMD ["/usr/sbin/postfix","start","-fg"]

RUN mkdir /run/php
COPY nginx.conf /etc/nginx/nginx.conf
COPY php.ini /etc/php/7.0/fpm/php.ini
COPY php.ini /etc/php/7.0/cgi/php.ini
COPY site.conf /etc/nginx/sites-enabled/default
COPY mulainginx.sh /start_nginx.sh
COPY start_php-fpm7.sh /start_php-fpm7.sh
COPY wrapper.sh /wrapper.sh
CMD chown www-data:www-data /var/www
CMD chown -R www-data:www-data /var/www/*
RUN chmod +x /start_nginx.sh /start_php-fpm7.sh /wrapper.sh
CMD ["/wrapper.sh"]
#CMD ["sh", "-c","service postfix start"]

RUN rm -rf /var/www/html/index.html
RUN rm -rf /var/www/html/dockerfile
RUN rm -rf /var/www/html/site.conf
RUN rm -rf /var/www/html/php.ini
RUN rm -rf /var/www/html/wrapper.sh
RUN rm -rf /var/www/html/start_php-fpm7.sh
RUN rm -rf /var/www/html/mulainginx.sh
RUN rm -rf /var/www/html/nginx.conf
